USE Project_BD
GO

CREATE SCHEMA TripPlanner
GO


CREATE TABLE TripPlanner.Person(
	Sex VARCHAR(6) NOT NULL,
	PfName VARCHAR(15) NOT NULL,
	PmName VARCHAR(15) NOT NULL,
	PlName VARCHAR(15) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	CC VARCHAR(8) NOT NULL PRIMARY KEY,
	PAddress VARCHAR(30) NOT NULL
);


CREATE TABLE TripPlanner.Trip(
	TrType VARCHAR(15) NOT NULL,
	TrInclude VARCHAR(50) NOT NULL,
	TrNoInclude VARCHAR(50) NOT NULL,
	ID INT NOT NULL PRIMARY KEY,
	Price INT NOT NULL,
	Duration INT NOT NULL,
	Departure_Date DATE NOT NULL,
	TrState VARCHAR(10) NOT NULL,
	Elaborator_CC VARCHAR(8) NOT NULL FOREIGN KEY REFERENCES TripPlanner.Person(CC)
);


CREATE TABLE TripPlanner.POInterest(
	Email VARCHAR(30) NOT NULL,
	Rating INT NOT NULL,
	PoIName VARCHAR(15) NOT NULL,
	Contact VARCHAR(15) NOT NULL PRIMARY KEY,
	Price INT NOT NULL,
	PoIAddress VARCHAR(30) NOT NULL
);

CREATE TABLE TripPlanner.Restaurant(
	RContact VARCHAR(15) UNIQUE FOREIGN KEY REFERENCES TripPlanner.POInterest(Contact),
	Stars INT NOT NULL,
	Specialty VARCHAR(15) NOT NULL 
);

CREATE TABLE TripPlanner.Museum(
	MContact VARCHAR(15) UNIQUE FOREIGN KEY REFERENCES TripPlanner.POInterest(Contact),
	Synopsis VARCHAR(100) NOT NULL,
	Theme VARCHAR(20) NOT NULL 
);

CREATE TABLE TripPlanner.Store(
	RContact VARCHAR(15) UNIQUE FOREIGN KEY REFERENCES TripPlanner.POInterest(Contact),
	SType VARCHAR(15) NOT NULL 
);

CREATE TABLE TripPlanner.PoIEvent(
	RContact VARCHAR(15) UNIQUE FOREIGN KEY REFERENCES TripPlanner.POInterest(Contact),
	EType VARCHAR(15) NOT NULL 
);



CREATE TABLE TripPlanner.Stay(
	Email VARCHAR(30) NOT NULL,
	Rating INT NOT NULL,
	SName VARCHAR(15) NOT NULL,
	Contact VARCHAR(15) NOT NULL PRIMARY KEY,
	SAddress VARCHAR(30) NOT NULL
);


CREATE TABLE TripPlanner.City(
	CName VARCHAR(15) NOT NULL PRIMARY KEY,
	Country VARCHAR(15) NOT NULL,
	Continent VARCHAR(15) NOT NULL,
	Stay_Contact VARCHAR(15) NOT NULL FOREIGN KEY REFERENCES TripPlanner.Stay(Contact),
	PoI_Contact VARCHAR(15) NOT NULL FOREIGN KEY REFERENCES TripPlanner.PoInterest(Contact)
);

